name: 3D Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yutori-saka/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: MUTHUKUMARAN005
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update 3D contrib graph"
          file_pattern: profile-3d-contrib/**
