name: 3D Contribution Graph

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/3d-contrib.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-3d-contrib@0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update 3D contrib graph"
          file_pattern: profile-3d-contrib/**
